import { readFileSync } from 'node:fs';
const s = readFileSync('/tmp/pr2r6_pl.json', 'utf8');
const p = JSON.parse(s);
console.log('payload size:', s.length, 'bytes ~', (s.length/1024).toFixed(1), 'KB');
console.log();
console.log('=== LEDGER RECONCILIATION (Check 9) ===');
console.log(JSON.stringify(p.ledger_reconciliation, null, 2));
console.log();
console.log('=== LEDGERS ===');
console.log('equipment:', 'count=', p.ledgers?.equipment?.total_count, 'amount=$'+p.ledgers?.equipment?.total_amount, 'cap=', p.ledgers?.equipment?.cap, 'rows.length=', p.ledgers?.equipment?.rows?.length, 'unresolved=', p.ledgers?.equipment?.unresolved_vendor_id_count);
console.log('repair:', 'count=', p.ledgers?.repair?.total_count, 'amount=$'+p.ledgers?.repair?.total_amount, 'cap=', p.ledgers?.repair?.cap, 'rows.length=', p.ledgers?.repair?.rows?.length, 'unresolved=', p.ledgers?.repair?.unresolved_vendor_id_count);
console.log('reimbursable:', 'count=', p.ledgers?.reimbursable?.total_count, 'amount=$'+p.ledgers?.reimbursable?.total_amount, 'cap=', p.ledgers?.reimbursable?.cap, 'rows.length=', p.ledgers?.reimbursable?.rows?.length, 'unresolved=', p.ledgers?.reimbursable?.unresolved_vendor_id_count);
console.log();
console.log('=== CARD CHARGES ===');
console.log('count=', p.card_charges?.total_count, 'amount=$'+p.card_charges?.total_amount, 'cap=', p.card_charges?.cap, 'rows.length=', p.card_charges?.rows?.length);
console.log();
console.log('=== VENDORS ===');
console.log('count=', p.vendors?.total_count, 'amount=$'+p.vendors?.total_amount, 'cap=', p.vendors?.cap, 'rows.length=', p.vendors?.rows?.length, 'unresolved=', p.vendors?.unresolved_count);
console.log('fragmentation:', JSON.stringify(p.vendors?.fragmentation, null, 2));
console.log();
console.log('=== FIRST 3 EQUIPMENT ROWS ===');
console.log(JSON.stringify(p.ledgers?.equipment?.rows?.slice(0,3), null, 2));
console.log();
console.log('=== FIRST 3 CARD CHARGE ROWS ===');
console.log(JSON.stringify(p.card_charges?.rows?.slice(0,3), null, 2));
console.log();
console.log('=== FIRST 3 VENDOR ROWS ===');
console.log(JSON.stringify(p.vendors?.rows?.slice(0,3), null, 2));
