// /api/academy/document
//
// Focus-view data feed. Returns everything the Academy needs to render
// one requirement in reading mode:
//   - doc               documents row: title, version, owner, shelf, dates
//   - content_html      pre-rendered HTML from document_content.html for
//                       the requested language (English only in v1).
//                       Rendered via dangerouslySetInnerHTML by the
//                       Focus view - same path the Playbook reader uses;
//                       no MDX re-rendering at read time.
//   - requirement       the specific academy_requirements row (this is
//                       the "why does this apply" ledger fact - cycle
//                       label, due date, minutes, doc version at issue)
//   - obligation        the source_section pointer + description
//   - cycle             human label + dates for the requirement's cycle
//
// Query params: ?req=<requirement_id>
//   The requirement_id is the source of truth. From it we resolve the
//   doc_id + obligation_key without trusting client-supplied keys. This
//   also silently protects against a viewer opening a requirement that
//   is not theirs - the query filter is worker_id = viewer's; a mismatched
//   requirement_id returns 404.
//
// Fenced by ACADEMY_PREVIEW_ONLY. TEST_MODE bypass mirrors the shell.
// Zero writes. No PII on the wire.

import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { getServiceClient } from "@/lib/supabase";
import {
  resolveAcademyIdentity,
  ACADEMY_PREVIEW_ONLY,
  ACADEMY_PREVIEW_ALLOWLIST,
} from "@/lib/academy/resolveIdentity";

export const dynamic = "force-dynamic";

function normEmail(e) {
  return String(e || "").trim().toLowerCase();
}

// Loose UUID validation. `academy_requirements.requirement_id` is a UUID
// generated by gen_random_uuid(); we sanity-check before hitting the DB
// so a garbage query string returns 400 fast instead of a PostgREST
// coercion error.
const UUID_RE = /^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$/;

export async function GET(request) {
  const testModeBypass =
    process.env.TEST_MODE === "true" && process.env.VERCEL !== "1";

  const session = await auth();
  const email = testModeBypass
    ? (ACADEMY_PREVIEW_ALLOWLIST[0] || "test@example.invalid")
    : normEmail(session?.user?.email);

  if (!email) {
    return NextResponse.json({ error: "unauthenticated" }, { status: 401 });
  }
  if (!testModeBypass && ACADEMY_PREVIEW_ONLY && !ACADEMY_PREVIEW_ALLOWLIST.includes(email)) {
    return NextResponse.json({ error: "forbidden" }, { status: 403 });
  }

  const { searchParams } = new URL(request.url);
  const requirementId = searchParams.get("req");
  if (!requirementId || !UUID_RE.test(requirementId)) {
    return NextResponse.json(
      { error: "bad_request", detail: "req query parameter must be a UUID" },
      { status: 400 }
    );
  }

  const supa = getServiceClient();

  let identity;
  try {
    identity = await resolveAcademyIdentity(email, { supa });
  } catch (err) {
    console.error("[api/academy/document] resolve threw:", err?.message || err);
    return NextResponse.json({ error: "server_error", scope: "identity" }, { status: 500 });
  }
  if (!identity) {
    return NextResponse.json({ error: "no_roster_row" }, { status: 404 });
  }

  // Load the requirement. Filter on worker_id = viewer's so a viewer
  // cannot pull someone else's requirement even if they know the UUID.
  // maybeSingle returns null for zero rows; we map to 404.
  const reqQ = await supa
    .from("academy_requirements")
    .select("requirement_id, worker_id, doc_id, obligation_key, doc_version, est_minutes, source, cycle_id, due_date, issued_at, waived_at, waive_reason")
    .eq("requirement_id", requirementId)
    .eq("worker_id", identity.workerId)
    .maybeSingle();
  if (reqQ.error) {
    console.error("[api/academy/document] requirement:", reqQ.error.message);
    return NextResponse.json({ error: "server_error", scope: "requirement" }, { status: 500 });
  }
  if (!reqQ.data) {
    return NextResponse.json({ error: "not_found" }, { status: 404 });
  }
  const req = reqQ.data;

  // Doc, obligation, cycle in parallel. Content is fetched in the same
  // batch - a single Focus-view page-load is one round-trip.
  const [docQ, obQ, cycleQ, contentQ] = await Promise.all([
    supa
      .from("documents")
      .select("id, title, doc_class, status, version, shelf, owner, approver, effective_date, last_reviewed, next_review, updated_at, card_line, summary")
      .eq("id", req.doc_id)
      .maybeSingle(),
    supa
      .from("academy_obligations")
      .select("doc_id, obligation_key, doc_version, source_section, description, type, cadence, est_minutes, applies_to, owner")
      .eq("doc_id", req.doc_id)
      .eq("obligation_key", req.obligation_key)
      .maybeSingle(),
    req.cycle_id != null
      ? supa
          .from("academy_cycles")
          .select("cycle_id, label, period_start, period_end, status, fiscal_year, fiscal_period_no")
          .eq("cycle_id", req.cycle_id)
          .maybeSingle()
      : Promise.resolve({ data: null, error: null }),
    supa
      .from("document_content")
      .select("html, content_hash, rendered_at")
      .eq("doc_id", req.doc_id)
      .eq("lang", "en")
      .maybeSingle(),
  ]);
  if (docQ.error) {
    console.error("[api/academy/document] doc:", docQ.error.message);
    return NextResponse.json({ error: "server_error", scope: "doc" }, { status: 500 });
  }
  if (obQ.error) {
    console.error("[api/academy/document] obligation:", obQ.error.message);
    return NextResponse.json({ error: "server_error", scope: "obligation" }, { status: 500 });
  }
  if (cycleQ.error) {
    console.error("[api/academy/document] cycle:", cycleQ.error.message);
    return NextResponse.json({ error: "server_error", scope: "cycle" }, { status: 500 });
  }
  if (contentQ.error) {
    console.error("[api/academy/document] content:", contentQ.error.message);
    return NextResponse.json({ error: "server_error", scope: "content" }, { status: 500 });
  }
  if (!docQ.data) {
    return NextResponse.json({ error: "not_found", scope: "doc" }, { status: 404 });
  }

  const doc = docQ.data;
  const ob = obQ.data || null;
  const cyc = cycleQ.data || null;
  const content = contentQ.data || null;

  return NextResponse.json({
    ok: true,
    doc: {
      id: doc.id,
      title: doc.title || doc.id,
      doc_class: doc.doc_class,
      status: doc.status,
      version: doc.version,
      shelf: doc.shelf,
      owner: doc.owner,
      approver: doc.approver,
      effective_date: doc.effective_date,
      last_reviewed: doc.last_reviewed,
      next_review: doc.next_review,
      updated_at: doc.updated_at,
      card_line: doc.card_line,
      summary: doc.summary,
    },
    content_html: content?.html || null,
    content_rendered_at: content?.rendered_at || null,
    requirement: {
      requirement_id: req.requirement_id,
      doc_id: req.doc_id,
      obligation_key: req.obligation_key,
      doc_version: req.doc_version,
      est_minutes: req.est_minutes,
      source: req.source,
      cycle_id: req.cycle_id,
      due_date: req.due_date,
      issued_at: req.issued_at,
      waived: req.waived_at != null,
    },
    obligation: ob
      ? {
          obligation_key: ob.obligation_key,
          doc_version: ob.doc_version,
          source_section: ob.source_section,
          description: ob.description,
          type: ob.type,
          cadence: ob.cadence,
          est_minutes: ob.est_minutes,
          applies_to: ob.applies_to,
          owner: ob.owner,
        }
      : null,
    cycle: cyc
      ? {
          cycle_id: cyc.cycle_id,
          label: cyc.label,
          period_start: cyc.period_start,
          period_end: cyc.period_end,
          status: cyc.status,
          fiscal_year: cyc.fiscal_year,
          fiscal_period_no: cyc.fiscal_period_no,
        }
      : null,
  });
}
