// ═══════════════════════════════════════════════════════════════════
// recordCopyPdf - generates the RECORD COPY PDF attached to N1.
// 2026-09-09.
// ═══════════════════════════════════════════════════════════════════
//
// Design authority: docs/design/KF_CONFIRMATION_EMAIL_RENDER.html.
// Brief: CC_PROMPT_CONFIRMATION_EMAIL.md (Kevin, 2026-09-09).
//
// The record copy is the operator's read of what was billed for
// their service week. Today N1 links to QuickBooks; most operators
// cannot open QBO. This document is the first time a chef can see
// the invoice lines for their own week.
//
// ─── Two invariants (Kevin ruling) ────────────────────────────────
//
// 1. Generated by us, not pulled from QuickBooks. Pulling QBO's PDF
//    would carry payment apparatus we cannot watermark or strip.
//    Generating our own lets us omit what should not be here
//    (bank details, "View and pay", invoice number) and add what
//    should (RECORD COPY title, watermark, approved-by attribution).
//
// 2. No QBO invoice number, ever. Even once QBO assigns one, this
//    document must not display it. A record copy bearing the real
//    invoice number is one step from being mistaken for the invoice.
//    Enforced by construction (this function has no access to the
//    invoice-number field) and asserted by
//    recordCopyPdf.test.mjs "no digit-run resembling an invoice #".
//
// ─── Multi-slot semantics ─────────────────────────────────────────
//
// TBJ finalizes into 3-8 QBO invoices in one action. This function
// produces ONE PDF covering the whole week (Kevin ruling 2026-09-09):
// the operator's mental model is "the week," not "the four slots."
// The pretax total sums across every slot; the same number appears
// on the email's fact-table.
//
// ─── pdf-lib over Chromium ────────────────────────────────────────
//
// pdf-lib is pure JS, no cold-start tax, no /tmp extraction. The
// record copy is a table + text + watermark + logo - every element
// is trivial in pdf-lib. See CC report to Kevin for the deployment-
// risk rationale.

import { PDFDocument, StandardFonts, rgb, degrees } from "pdf-lib";
import { PFS_LOGO_PNG_BASE64 } from "./pfsLogoBase64.js";

// ─── Color palette (matches the render) ───────────────────────────
const NAVY     = rgb(0x1A / 255, 0x30 / 255, 0x50 / 255); // #1A3050
const INK      = rgb(0x0F / 255, 0x17 / 255, 0x2A / 255); // #0F172A
const N700     = rgb(0x47 / 255, 0x55 / 255, 0x69 / 255); // #475569
const N500     = rgb(0x64 / 255, 0x74 / 255, 0x8B / 255); // #64748B
const N400     = rgb(0x94 / 255, 0xA3 / 255, 0xB8 / 255); // #94A3B8
const N100     = rgb(0xF1 / 255, 0xF5 / 255, 0xF9 / 255); // #F1F5F9
const N200     = rgb(0xE2 / 255, 0xE8 / 255, 0xF0 / 255); // #E2E8F0
const RED      = rgb(0xB3 / 255, 0x26 / 255, 0x1E / 255); // #B3261E
const WATERMARK_ALPHA = 0.13;                              // matches render's ~13%

// ─── Layout constants (US Letter, portrait) ───────────────────────
const PAGE_W = 612;    // 8.5"
const PAGE_H = 792;    // 11"
const MARGIN = 40;
const LOGO_DISPLAY_W = 132; // matches render .ph .lg { width:132px }

// ─── Filename normalization ───────────────────────────────────────
//
// Render shape: TBR-FL_week-of-Aug-25_record-copy.pdf.
// Rules (Kevin ruling 2026-09-09):
//   - Strip spaces: "TBR - FL" -> "TBR-FL"
//   - MMM-DD week start in UTC
//   - Reject em-dash (positive test fails if one is ever introduced)
//   - ASCII-only after normalization

const EM_DASH = "—";

export function buildRecordCopyFilename(accountKey, weekStartISO) {
  if (accountKey && String(accountKey).includes(EM_DASH)) {
    throw new Error(
      `buildRecordCopyFilename: account key contains em-dash (U+2014): ${JSON.stringify(accountKey)}. Ops accounts use ASCII hyphens; fix upstream.`
    );
  }
  const cleanAccount = String(accountKey || "").replace(/\s+/g, "");
  const d = new Date(`${weekStartISO}T12:00:00Z`);
  const month = d.toLocaleDateString("en-US", { month: "short", timeZone: "UTC" });
  const day   = d.toLocaleDateString("en-US", { day: "numeric", timeZone: "UTC" });
  return `${cleanAccount}_week-of-${month}-${day}_record-copy.pdf`;
}

// ─── Date formatters (UTC to match invoice-line semantics) ────────

function fmtDate(iso, opts) {
  if (!iso) return "";
  return new Date(`${iso}T12:00:00Z`).toLocaleDateString("en-US", { timeZone: "UTC", ...opts });
}

function fmtLineDate(iso) {
  // MM/DD/YYYY (matches render)
  return fmtDate(iso, { month: "2-digit", day: "2-digit", year: "numeric" });
}

function fmtWeekRangeLong(startISO, endISO) {
  const s = fmtDate(startISO, { weekday: "short", month: "short", day: "numeric" });
  const e = fmtDate(endISO,   { weekday: "short", month: "short", day: "numeric" });
  return `${s} - ${e}`;
}

function fmtCents(cents) {
  const dollars = Math.round(Number(cents) || 0) / 100;
  return dollars.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

// ─── Line-item aggregation across slots ───────────────────────────
//
// invoiceRecords[]: per-slot; each has lineItems[]. Flatten into one
// array preserving order (date, then slot). Returns a normalized
// shape recordCopy renders + a pretaxCents total that the caller
// asserts against the email's fact-table.

function flattenLines(invoiceRecords) {
  const lines = [];
  let pretaxCents = 0;
  for (const rec of invoiceRecords || []) {
    for (const li of rec.lineItems || []) {
      const qty = Number(li.qty) || 0;
      const rateCents = Number(li.rateCents) || 0;
      const amountCents = Number(li.amountCents ?? (qty * rateCents)) || 0;
      lines.push({
        serviceName: String(li.serviceName || ""),
        serviceDate: String(li.serviceDate || ""),
        qty,
        rateCents,
        amountCents,
      });
      pretaxCents += amountCents;
    }
  }
  // Sort by date then by service name so multi-slot weeks group cleanly.
  lines.sort((a, b) => {
    if (a.serviceDate !== b.serviceDate) return a.serviceDate < b.serviceDate ? -1 : 1;
    return a.serviceName < b.serviceName ? -1 : 1;
  });
  return { lines, pretaxCents };
}

// ─── Simple text width measurement (embedded font metrics) ────────

function measure(font, text, size) {
  return font.widthOfTextAtSize(String(text), size);
}

// Truncate `text` with an ellipsis if wider than maxWidth at `size`.
function truncateToWidth(font, text, size, maxWidth) {
  if (measure(font, text, size) <= maxWidth) return text;
  const ell = "…";
  let s = String(text);
  while (s.length > 1 && measure(font, s + ell, size) > maxWidth) {
    s = s.slice(0, -1);
  }
  return s + ell;
}

// ─── Main entry: build the RECORD COPY PDF ────────────────────────
//
// invoiceRecords[] shape (matches qboNotifications' expectations):
//   { invoiceSlot, pretaxTotalCents, lineItems: [{ serviceName,
//     serviceDate, qty, rateCents, amountCents }] }
//
// Returns { pdfBase64, pdfBuffer, filename, pretaxCents }.
// pretaxCents is the source of truth for the "email $ == PDF $"
// assertion in n1Body.
//
// @param {Object} args
// @param {string} args.accountKey        e.g. "TBR - FL"
// @param {string} args.accountLabel      Optional pretty name (e.g. "Tampa Bay Rays")
// @param {string} args.weekStart         ISO Monday
// @param {string} args.weekEnd           ISO Sunday
// @param {string} args.finalizedDateISO  ISO date the week finalized (for the "Finalized" meta row)
// @param {string} args.approvedByLabel   Text for the "Approved by" meta row (compute in n1Body per multi-approver rule)
// @param {Array}  args.invoiceRecords    Per-slot invoice records (aggregated across the week)
// @returns {Promise<{ pdfBase64: string, pdfBuffer: Buffer, filename: string, pretaxCents: number, lineCount: number }>}
export async function buildRecordCopyPdf({
  accountKey,
  accountLabel,
  weekStart,
  weekEnd,
  finalizedDateISO,
  approvedByLabel,
  invoiceRecords,
}) {
  const { lines, pretaxCents } = flattenLines(invoiceRecords);
  const filename = buildRecordCopyFilename(accountKey, weekStart);

  const pdfDoc = await PDFDocument.create();
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold    = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const logoImg     = await pdfDoc.embedPng(Buffer.from(PFS_LOGO_PNG_BASE64, "base64"));
  const logoScale   = LOGO_DISPLAY_W / logoImg.width;
  const logoH       = logoImg.height * logoScale;

  const page = pdfDoc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;

  // ── Header row: company block top-left, PFS logo top-right ─────
  page.drawText("CJK Foods, LLC dba Kitchfix", {
    x: MARGIN, y: y - 12, font: fontBold, size: 12, color: INK,
  });
  page.drawText("2332 W Grand Ave", {
    x: MARGIN, y: y - 26, font: fontRegular, size: 9, color: N500,
  });
  page.drawText("Chicago, IL 60612", {
    x: MARGIN, y: y - 37, font: fontRegular, size: 9, color: N500,
  });
  page.drawImage(logoImg, {
    x: PAGE_W - MARGIN - LOGO_DISPLAY_W,
    y: y - logoH,
    width: LOGO_DISPLAY_W,
    height: logoH,
  });

  y -= Math.max(logoH, 45) + 24;

  // ── Title: RECORD COPY + red subtitle ──────────────────────────
  page.drawText("RECORD COPY", {
    x: MARGIN, y: y - 18, font: fontBold, size: 18, color: NAVY,
  });
  page.drawText("Not an invoice · internal record only", {
    x: MARGIN, y: y - 32, font: fontBold, size: 8, color: RED,
  });
  y -= 46;

  // ── Meta row: account/week (left) + finalized/approved (right) ─
  // Widen the right block to 260px so a multi-approver week like
  // "Joe Coppolino and Desiree Colone" can fit without ellipsis
  // truncation in the "Approved by" value. Left column still fits
  // "TBR - FL · Tampa Bay Rays" without wrapping at 10pt bold.
  const metaFontSize = 10;
  const metaLineH = 15;
  const rightColX = PAGE_W - MARGIN - 260;

  page.drawText("Account", {
    x: MARGIN, y, font: fontRegular, size: metaFontSize, color: N400,
  });
  const accountText = accountLabel
    ? `${accountKey} · ${accountLabel}`
    : accountKey;
  page.drawText(String(accountText), {
    x: MARGIN + 70, y, font: fontBold, size: metaFontSize, color: INK,
  });

  page.drawText("Finalized", {
    x: rightColX, y, font: fontRegular, size: metaFontSize, color: N400,
  });
  page.drawText(fmtDate(finalizedDateISO, { month: "short", day: "numeric", year: "numeric" }), {
    x: rightColX + 70, y, font: fontBold, size: metaFontSize, color: INK,
  });

  y -= metaLineH;

  page.drawText("Service week", {
    x: MARGIN, y, font: fontRegular, size: metaFontSize, color: N400,
  });
  page.drawText(fmtWeekRangeLong(weekStart, weekEnd), {
    x: MARGIN + 70, y, font: fontBold, size: metaFontSize, color: INK,
  });

  page.drawText("Approved by", {
    x: rightColX, y, font: fontRegular, size: metaFontSize, color: N400,
  });
  // Approved-by can be a long multi-name string ("Joe Coppolino, Desiree
  // Colone, and Steve Groves"). Truncate to fit the right column width.
  const approvedTruncated = truncateToWidth(fontBold, approvedByLabel || "—",
    metaFontSize, PAGE_W - MARGIN - (rightColX + 70));
  page.drawText(approvedTruncated, {
    x: rightColX + 70, y, font: fontBold, size: metaFontSize, color: INK,
  });

  y -= 26;

  // ── Line table: service, date, qty, rate, amount ───────────────
  // Column layout (fitting inside content width PAGE_W - 2*MARGIN = 532):
  //   Service:   250w  (left)
  //   Date:       80w  (left)
  //   Qty:        50w  (right)
  //   Rate:       70w  (right)
  //   Amount:     82w  (right)
  const COL_X = {
    service: MARGIN,
    date:    MARGIN + 250,
    qtyR:    MARGIN + 250 + 80 + 50,
    rateR:   MARGIN + 250 + 80 + 50 + 70,
    amtR:    MARGIN + 250 + 80 + 50 + 70 + 82,
  };
  const HEADER_FONT_SIZE = 8;
  const ROW_FONT_SIZE = 9;
  const ROW_H = 15;

  // Header row on N100 background
  page.drawRectangle({
    x: MARGIN - 4, y: y - 11, width: PAGE_W - 2 * MARGIN + 8, height: 16, color: N100,
  });
  page.drawText("SERVICE", { x: COL_X.service, y: y - 8, font: fontBold, size: HEADER_FONT_SIZE, color: N500 });
  page.drawText("DATE",    { x: COL_X.date,    y: y - 8, font: fontBold, size: HEADER_FONT_SIZE, color: N500 });
  drawRightAligned(page, "QTY",    COL_X.qtyR,  y - 8, fontBold, HEADER_FONT_SIZE, N500);
  drawRightAligned(page, "RATE",   COL_X.rateR, y - 8, fontBold, HEADER_FONT_SIZE, N500);
  drawRightAligned(page, "AMOUNT", COL_X.amtR,  y - 8, fontBold, HEADER_FONT_SIZE, N500);
  y -= 20;

  const MAX_SERVICE_W = 246;
  const AMOUNT_FLOOR = MARGIN + 30; // stop-drawing floor for the last row before footer

  // Draw as many rows as fit. If we spill past the last row, wrap
  // long weeks to a second page (rare but multi-slot TBJ + full 7
  // days could hit it).
  let currentPage = page;
  let currentY = y;

  for (let i = 0; i < lines.length; i++) {
    const li = lines[i];

    if (currentY < AMOUNT_FLOOR + ROW_H) {
      // Page break. Add a new page, redraw table header, continue.
      currentPage = pdfDoc.addPage([PAGE_W, PAGE_H]);
      currentY = PAGE_H - MARGIN;
      // Watermark drawn later on every page.
      currentPage.drawRectangle({
        x: MARGIN - 4, y: currentY - 11, width: PAGE_W - 2 * MARGIN + 8, height: 16, color: N100,
      });
      currentPage.drawText("SERVICE", { x: COL_X.service, y: currentY - 8, font: fontBold, size: HEADER_FONT_SIZE, color: N500 });
      currentPage.drawText("DATE",    { x: COL_X.date,    y: currentY - 8, font: fontBold, size: HEADER_FONT_SIZE, color: N500 });
      drawRightAligned(currentPage, "QTY",    COL_X.qtyR,  currentY - 8, fontBold, HEADER_FONT_SIZE, N500);
      drawRightAligned(currentPage, "RATE",   COL_X.rateR, currentY - 8, fontBold, HEADER_FONT_SIZE, N500);
      drawRightAligned(currentPage, "AMOUNT", COL_X.amtR,  currentY - 8, fontBold, HEADER_FONT_SIZE, N500);
      currentY -= 20;
    }

    const serviceText = truncateToWidth(fontRegular, li.serviceName, ROW_FONT_SIZE, MAX_SERVICE_W);
    currentPage.drawText(serviceText, {
      x: COL_X.service, y: currentY, font: fontRegular, size: ROW_FONT_SIZE, color: INK,
    });
    currentPage.drawText(fmtLineDate(li.serviceDate), {
      x: COL_X.date, y: currentY, font: fontRegular, size: ROW_FONT_SIZE, color: INK,
    });
    drawRightAligned(currentPage, String(li.qty), COL_X.qtyR, currentY, fontRegular, ROW_FONT_SIZE, INK);
    drawRightAligned(currentPage, fmtCents(li.rateCents), COL_X.rateR, currentY, fontRegular, ROW_FONT_SIZE, INK);
    drawRightAligned(currentPage, fmtCents(li.amountCents), COL_X.amtR, currentY, fontRegular, ROW_FONT_SIZE, INK);

    // Bottom border for the row
    currentPage.drawLine({
      start: { x: MARGIN, y: currentY - 4 },
      end:   { x: PAGE_W - MARGIN, y: currentY - 4 },
      thickness: 0.5,
      color: N100,
    });

    currentY -= ROW_H;
  }

  // Total row (heavier top border, larger font, right-aligned)
  currentY -= 4;
  currentPage.drawLine({
    start: { x: MARGIN, y: currentY + 6 },
    end:   { x: PAGE_W - MARGIN, y: currentY + 6 },
    thickness: 1.5,
    color: N200,
  });
  currentPage.drawText("Pre-tax total", {
    x: COL_X.service, y: currentY - 8, font: fontBold, size: 11, color: INK,
  });
  drawRightAligned(currentPage, fmtCents(pretaxCents), COL_X.amtR, currentY - 8, fontBold, 12, INK);
  currentY -= 30;

  // ── Footer: not-an-invoice disclaimer ──────────────────────────
  const footerLine1 = "This document records what was sent to billing for the service week above.";
  const footerLine2 = "It is not an invoice and cannot be paid. The client invoice is issued separately from QuickBooks.";
  currentPage.drawLine({
    start: { x: MARGIN, y: currentY }, end: { x: PAGE_W - MARGIN, y: currentY },
    thickness: 0.5, color: N100,
  });
  currentY -= 14;
  drawCentered(currentPage, footerLine1, PAGE_W / 2, currentY, fontRegular, 8.5, N400);
  currentY -= 11;
  drawCentered(currentPage, footerLine2, PAGE_W / 2, currentY, fontBold,    8.5, N400);

  // ── Watermark on every page (diagonal NOT AN INVOICE) ──────────
  // Drawn last so it overlays the content. pdf-lib does support
  // opacity on drawText; 0.13 matches the render.
  for (const p of pdfDoc.getPages()) {
    drawWatermark(p, fontBold);
  }

  // useObjectStreams:false emits an uncompressed xref so unit tests
  // can grep the content streams for "NOT AN INVOICE" / "RECORD COPY"
  // / positive assertions that no invoice-number pattern leaked. The
  // file-size cost is small (~10-15% larger) and the readability
  // trade is worth it - the alternative is opaque compressed streams
  // that only mount-verify could inspect.
  const pdfBytes = await pdfDoc.save({ useObjectStreams: false });
  const pdfBuffer = Buffer.from(pdfBytes);
  const pdfBase64 = pdfBuffer.toString("base64");

  return {
    pdfBase64,
    pdfBuffer,
    filename,
    pretaxCents,
    lineCount: lines.length,
  };
}

// ─── Drawing helpers ──────────────────────────────────────────────

function drawRightAligned(page, text, xRight, y, font, size, color) {
  const w = font.widthOfTextAtSize(String(text), size);
  page.drawText(String(text), { x: xRight - w, y, font, size, color });
}

function drawCentered(page, text, xCenter, y, font, size, color) {
  const w = font.widthOfTextAtSize(String(text), size);
  page.drawText(String(text), { x: xCenter - w / 2, y, font, size, color });
}

function drawWatermark(page, fontBold) {
  const text = "NOT AN INVOICE";
  const size = 72;
  const w = fontBold.widthOfTextAtSize(text, size);
  // Rotate -24deg (matches render). Position at center; pdf-lib
  // rotates around the origin so translate first.
  page.drawText(text, {
    x: (PAGE_W - w) / 2,
    y: PAGE_H / 2 - size / 2,
    font: fontBold,
    size,
    color: RED,
    opacity: WATERMARK_ALPHA,
    rotate: degrees(-24),
    // rotate origin is drawing baseline; the visual center will
    // shift a bit but the diagonal reads clearly.
  });
}

// ─── Approved-by phrase computer ──────────────────────────────────
//
// Kevin ruling 2026-09-09: "Do not write copy that claims one person
// did all of it when the data says otherwise."
//
// Input: array of {reviewedBy, reviewedAt} rows across the week's
// service days (already filtered to review_status='approved').
// Output: { approvers, lede, meta } where:
//   approvers    - unique display names, ordered by day-count DESC
//                  then earliest-timestamp ASC (deterministic)
//   lede         - the sentence for the email body lede
//   meta         - the shorter phrase for the PDF's "Approved by" meta row
//
// Cases (finalizerName provided for the "sent to billing" clause):
//   1 approver, is finalizer: "Joe Coppolino approved every day and
//                              sent TBR - FL to billing."
//   1 approver, not finalizer: "Desiree Colone approved every day.
//                              Joe Coppolino sent TBR - FL to billing."
//   2 approvers:              "Joe Coppolino and Desiree Colone approved
//                              the week. Joe Coppolino sent TBR - FL
//                              to billing."
//   3+ approvers:             "Joe Coppolino, Desiree Colone, and Steve
//                              Groves approved the week. ..."
//   >3 approvers:             top 3 by count, "and 2 others"
//
// The finalizer is always named as the "sent to billing" actor,
// even when they overlap with the approver set (natural repetition
// is preferred over ambiguity).

export function computeApproverPhrase({ reviewRows, finalizerName, accountKey }) {
  const counts = new Map();
  const earliestTs = new Map();
  for (const r of reviewRows || []) {
    const name = (r?.reviewedBy || "").trim();
    if (!name) continue;
    counts.set(name, (counts.get(name) || 0) + 1);
    if (r.reviewedAt) {
      const prev = earliestTs.get(name);
      if (!prev || String(r.reviewedAt) < String(prev)) {
        earliestTs.set(name, r.reviewedAt);
      }
    }
  }
  const uniqueApprovers = Array.from(counts.keys()).sort((a, b) => {
    // Higher count first
    if (counts.get(b) !== counts.get(a)) return counts.get(b) - counts.get(a);
    // Tie-break: earliest timestamp
    const ta = earliestTs.get(a) || "";
    const tb = earliestTs.get(b) || "";
    if (ta !== tb) return ta < tb ? -1 : 1;
    return a < b ? -1 : 1;
  });

  const acct = accountKey || "";
  const submitterClause = finalizerName
    ? `${finalizerName} sent ${acct} to billing.`
    : `${acct} was sent to billing.`;

  if (uniqueApprovers.length === 0) {
    return {
      approvers: [],
      lede: submitterClause,
      meta: finalizerName || "—",
    };
  }

  if (uniqueApprovers.length === 1) {
    const only = uniqueApprovers[0];
    if (finalizerName && only.toLowerCase() === finalizerName.toLowerCase()) {
      // Single approver == finalizer. Render's exact wording.
      return {
        approvers: [only],
        lede: `${only} approved every day and sent ${acct} to billing.`,
        meta: only,
      };
    }
    return {
      approvers: [only],
      lede: `${only} approved every day. ${submitterClause}`,
      meta: only,
    };
  }

  // 2+ approvers.
  const shown = uniqueApprovers.slice(0, 3);
  const overflow = uniqueApprovers.length - shown.length;
  let joined;
  if (shown.length === 2) {
    joined = `${shown[0]} and ${shown[1]}`;
  } else if (overflow > 0) {
    // 3 shown + overflow. Drop the Oxford before the last-shown so
    // the sentence reads "A, B, C and N others" (natural) instead
    // of "A, B, and C and N others" (double "and").
    joined = `${shown[0]}, ${shown[1]}, ${shown[2]} and ${overflow} other${overflow === 1 ? "" : "s"}`;
  } else {
    // Exactly 3 approvers - Oxford comma is correct.
    joined = `${shown[0]}, ${shown[1]}, and ${shown[2]}`;
  }
  return {
    approvers: uniqueApprovers,
    lede: `${joined} approved the week. ${submitterClause}`,
    meta: joined,
  };
}
