-- R-114 PR 2 · item 6 · load 3500.2 vehicle insurance into purchasing_actuals
--
-- Kevin ruling 2026-09-17 (route A). "R-73 defines actuals as bill.com +
-- Rippling + inventory + credits; insurance is a monthly finance line
-- and must arrive as data." So we load it as data rather than a
-- resolver-layer fallback out of pnl_actuals.
--
-- The board's vehicle bucket reads
--   purchasing_actuals WHERE gl_line_code LIKE '3500%'
-- (via GL_PREFIX_FOR_BUCKET.vehicle in src/app/kpi/purchasing/lib/board.js).
-- Today only 3500.4 fuel lands in that table; 3500.2 insurance sits in
-- pnl_actuals unread. This loads the P1-P8 pnl_actuals values into
-- purchasing_actuals and adds a manual P9 row for TBJ - FL (Kevin's
-- confirmed value; finance P9 P&L not yet loaded to pnl_actuals).
--
-- Idempotent via the unique (source, source_line_id) index. Rerunning
-- updates amount + txn_date to the pnl_actuals figure of record;
-- everything else is stable.
--
-- P9 CIN - KY 3500.2 is NOT loaded here — CIN-KY had P1-P8 insurance
-- (~$273/period) but finance has not published P9 yet and Kevin has
-- not confirmed a P9 figure. Flag for the next finance load.

BEGIN;

INSERT INTO purchasing_actuals (
  source, source_bill_id, source_line_id,
  account_key, excluded, gl_line_code, gl_bucket,
  txn_date, posting_date, amount, vendor_or_merchant, paid,
  approx_date, derived_at, reason
)
SELECT
  'pnl_finance_load'                                                 AS source,
  'pnl_actuals::' || account_key || '::FY' || fiscal_year || '::P' || period_no AS source_bill_id,
  account_key || '::FY' || fiscal_year || '::P' || period_no || '::3500.2' AS source_line_id,
  account_key,
  false                                                              AS excluded,
  '3500.2'                                                           AS gl_line_code,
  'vehicle'                                                          AS gl_bucket,
  -- txn_date = period end (FY2026 P{n} ends on 2025-12-29 + 28n - 1 days)
  ('2025-12-29'::date + (period_no * 28 - 1) * INTERVAL '1 day')::date AS txn_date,
  ('2025-12-29'::date + (period_no * 28 - 1) * INTERVAL '1 day')::date AS posting_date,
  actual                                                             AS amount,
  'Vehicle Insurance (finance)'                                      AS vendor_or_merchant,
  true                                                               AS paid,
  false                                                              AS approx_date,
  now()                                                              AS derived_at,
  'R-114 PR 2 item 6 · 3500.2 finance load'                          AS reason
FROM pnl_actuals
WHERE line_code = '3500.2'
  AND actual IS NOT NULL AND actual <> 0
ON CONFLICT (source, source_line_id) DO UPDATE
  SET amount    = EXCLUDED.amount,
      txn_date  = EXCLUDED.txn_date,
      derived_at = EXCLUDED.derived_at;

-- Manual P9 bootstrap for TBJ - FL only. Finance has not loaded P9 P&L
-- to pnl_actuals yet; Kevin ruled the P9 vehicle insurance value at
-- $611.00 (matching P8's $607.10 monthly pattern). Once finance loads
-- P9 into pnl_actuals, this row can be regenerated by the SELECT block
-- above and will UPDATE cleanly via the ON CONFLICT clause (same
-- source + source_line_id).
INSERT INTO purchasing_actuals (
  source, source_bill_id, source_line_id,
  account_key, excluded, gl_line_code, gl_bucket,
  txn_date, posting_date, amount, vendor_or_merchant, paid,
  approx_date, derived_at, reason
)
VALUES (
  'pnl_finance_load',
  'pnl_actuals::TBJ - FL::FY2026::P9',
  'TBJ - FL::FY2026::P9::3500.2',
  'TBJ - FL',
  false,
  '3500.2',
  'vehicle',
  '2026-09-06'::date,
  '2026-09-06'::date,
  611.00,
  'Vehicle Insurance (finance)',
  true,
  false,
  now(),
  'R-114 PR 2 item 6 · P9 manual bootstrap (Kevin ruling 2026-09-17)'
)
ON CONFLICT (source, source_line_id) DO UPDATE
  SET amount    = EXCLUDED.amount,
      txn_date  = EXCLUDED.txn_date,
      derived_at = EXCLUDED.derived_at;

COMMIT;

-- Verification queries (run these after the migration):
--
-- 1. Expected row count: pnl_actuals has 16 rows with 3500.2 non-zero
--    (TBJ - FL P1-P8, CIN - KY P1-P8) + 1 P9 TBJ - FL manual = 17 total.
--
--    SELECT COUNT(*) FROM purchasing_actuals
--    WHERE source = 'pnl_finance_load' AND gl_line_code = '3500.2';
--
--    Expected: 17
--
-- 2. TBJ - FL P9 vehicle total should read $611 + $124.19 fuel = $735.19.
--
--    SELECT gl_line_code, SUM(amount) FROM purchasing_actuals
--    WHERE account_key = 'TBJ - FL'
--      AND gl_line_code LIKE '3500%'
--      AND txn_date BETWEEN '2026-08-10' AND '2026-09-06'
--      AND NOT excluded
--    GROUP BY gl_line_code;
--
--    Expected: 3500.2 → $611.00, 3500.4 → $124.19
