-- ═══════════════════════════════════════════════════════════════
-- PR 5.1 - Project 3 Module 5: Vendor PG schema
-- ═══════════════════════════════════════════════════════════════
--
-- Creates the 3 vendor tables (vendors, vendor_aliases, vendor_accounts)
-- per docs/FINANCE_STACK_PLAN.md Section 2.2. RLS disabled per the
-- Section 8 service-role-only decision lock; row-level filtering is a
-- separate AUTH_MODEL.md follow-up (see Section 2.4).
--
-- Idempotency notes:
--   * vendors.client_uuid UNIQUE replaces today's read-modify-write
--     F19b dedup pattern in handleInvoicePost vendor-add.
--   * vendor_accounts.client_uuid UNIQUE same role for the account
--     half of vendor-add.
--   * vendor_aliases UNIQUE (vendor_id, alias_normalized) collapses
--     the multi-writer race today between learnVendorAlias /
--     vendor-merge / vendor-master-update.
--
-- Cross-store coordination notes:
--   * vendors.id is TEXT (not UUID) because the natural key is
--     '${prefix}-${100-999}' generated by F19a at handler time, and
--     both stores must agree on the same ID for dual-write.
--
-- DDL is idempotent (IF NOT EXISTS) so re-running the file is safe.

-- Prerequisite: pgcrypto extension (gen_random_uuid).
-- Already enabled from prior modules but the IF NOT EXISTS guard
-- makes this idempotent.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────────────────────────
-- vendors
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vendors (
  id              TEXT PRIMARY KEY,                          -- vendorId, e.g. "FRE-448"
  name            TEXT NOT NULL,
  category        TEXT,
  website         TEXT,
  notes           TEXT,
  created_by      TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  client_uuid     UUID UNIQUE,                                -- F19b idempotency
  deleted_at      TIMESTAMPTZ                                 -- soft-delete (replaces 'DELETED' sentinel)
);

CREATE INDEX IF NOT EXISTS vendors_name_idx
  ON vendors (lower(name)) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS vendors_category_idx
  ON vendors (category) WHERE deleted_at IS NULL;

-- ─────────────────────────────────────────────────────────────
-- vendor_aliases
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vendor_aliases (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id        TEXT NOT NULL REFERENCES vendors(id) ON DELETE CASCADE,
  alias_text       TEXT NOT NULL,
  alias_normalized TEXT GENERATED ALWAYS AS (
                     lower(regexp_replace(alias_text, '[^a-zA-Z0-9 ]', '', 'g'))
                   ) STORED,
  source           TEXT NOT NULL,                              -- 'manual', 'ocr_learned', 'merge'
  learned_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  learned_by       TEXT,                                       -- email or 'system'

  UNIQUE (vendor_id, alias_normalized)                         -- prevent duplicate aliases per vendor
);

CREATE INDEX IF NOT EXISTS vendor_aliases_alias_idx
  ON vendor_aliases (alias_normalized);

-- ─────────────────────────────────────────────────────────────
-- vendor_accounts
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS vendor_accounts (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  vendor_id             TEXT NOT NULL REFERENCES vendors(id),
  account_key           TEXT NOT NULL CHECK (
                          account_key ~ '^[A-Z]{3}( - [A-Z]{2,})?( - [HV])?$'
                          OR account_key = 'CORP'
                        ),                                              -- enforce canonical "CIN - OH" format per S3
  customer_account_num  TEXT,
  sales_rep_name        TEXT,
  sales_rep_phone       TEXT,
  sales_rep_email       TEXT,
  delivery_days         TEXT,
  cutoff_time           TEXT,
  delivery_method       TEXT,
  portal_url            TEXT,
  portal_username       TEXT,                                          -- plaintext per Q6 (intentional)
  portal_password       TEXT,                                          -- plaintext per Q6 (intentional)
  payment_terms         TEXT,
  min_order             TEXT,
  active                BOOLEAN NOT NULL DEFAULT true,
  created_by            TEXT NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  account_notes         TEXT,
  client_uuid           UUID UNIQUE,                                   -- F19b idempotency

  UNIQUE (vendor_id, account_key)
);

CREATE INDEX IF NOT EXISTS vendor_accounts_account_idx
  ON vendor_accounts (account_key);
CREATE INDEX IF NOT EXISTS vendor_accounts_active_idx
  ON vendor_accounts (account_key, active);

-- ─────────────────────────────────────────────────────────────
-- RLS: service-role only (per Section 8 lock)
-- ─────────────────────────────────────────────────────────────
-- Today access is "any authenticated user can read/write all finance
-- tables" (intentional per TEAM_KNOWLEDGE). Project 3 cutover keeps
-- the same posture: service role only, no row-level filtering. The
-- application layer's OPS_LEADERSHIP_EMAILS allow-list remains
-- authoritative. Future AUTH_MODEL.md work may add per-role policies;
-- not in scope here.

ALTER TABLE vendors          DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_aliases   DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendor_accounts  DISABLE ROW LEVEL SECURITY;

-- ─────────────────────────────────────────────────────────────
-- GRANTS: match the project convention (service_role has full DML;
-- anon + authenticated have metadata-only access, no DML)
-- ─────────────────────────────────────────────────────────────
-- Required because the Supabase project does not have a
-- default-privileges grant configured. Every new table needs explicit
-- GRANT statements to be queryable via PostgREST (which is what
-- supabase-js uses). Caught by scripts/verify-pr-5-1-schema.mjs:
-- without these grants, every PostgREST request returns "permission
-- denied for table X" even with RLS disabled.
--
-- Mirror the pattern from accounts/submissions/news_interactions:
--   service_role:  SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE  (7)
--   anon:          REFERENCES, TRIGGER, TRUNCATE only                              (3, no DML)
--   authenticated: REFERENCES, TRIGGER, TRUNCATE only                              (3, no DML)
--
-- For future Project 3 schema PRs (6.x, 7.x), include the equivalent
-- GRANT block for the tables created in that PR.
--
-- GRANT is idempotent - re-running on tables that already have the
-- grant is a no-op.

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON vendors          TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON vendor_aliases   TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON vendor_accounts  TO service_role;

GRANT REFERENCES, TRIGGER, TRUNCATE ON vendors          TO anon, authenticated;
GRANT REFERENCES, TRIGGER, TRUNCATE ON vendor_aliases   TO anon, authenticated;
GRANT REFERENCES, TRIGGER, TRUNCATE ON vendor_accounts  TO anon, authenticated;

-- ─────────────────────────────────────────────────────────────
-- Post-DDL verification (run manually after applying)
-- ─────────────────────────────────────────────────────────────
-- SELECT count(*) FROM vendors;          -- expect 0
-- SELECT count(*) FROM vendor_aliases;   -- expect 0
-- SELECT count(*) FROM vendor_accounts;  -- expect 0
--
-- CHECK constraint smoke test (expect ERROR):
--   INSERT INTO vendor_accounts (vendor_id, account_key, created_by)
--   VALUES ('TEST-001', 'cin-oh', 'test@example.com');
--   -- should reject with violates check constraint "vendor_accounts_account_key_check"
