-- ─────────────────────────────────────────────────────────────────────────────
-- pr-7-10-opd-content-table.sql
-- Project OPD · Phase A re-point · rendered display HTML store
-- ─────────────────────────────────────────────────────────────────────────────
--
-- Creates document_content as the store for precomputed display HTML
-- (the reader will source from this table in a later PR; this migration
-- only stands it up - the projection script populates it).
--
-- One row per (doc_id, lang). Bilingual docs get two rows: one en, one es.
-- content_hash is the SHA-256 of the resolved-markdown source so the
-- projection can short-circuit re-rendering when nothing changed.
-- rendered_at is the wall-clock timestamp of the render.
--
-- The MDX projection writes here; the reader reads here; nothing else
-- touches the table. The catalog (documents) stays the structural row;
-- this table holds the rendered prose body.
--
-- WHAT this does:
--   1. CREATE TABLE document_content.
--   2. RLS disabled + service_role grants matching the other OPD tables.
--   3. No backfill - the projection populates it.
--
-- IDEMPOTENT:
--   CREATE TABLE IF NOT EXISTS. Re-running is safe.
--
-- ROLLBACK:
--   DROP TABLE IF EXISTS document_content;
--   Safe: no FK targets it; the reader has not yet read from it (later PR).
--
-- COORDINATION:
--   Apply before running the projection script (scripts/content/project-
--   catalog.mjs --apply). The dry-run path does NOT touch this table.
--
-- VERIFY (after apply):
--   SELECT count(*) FROM document_content;
--   -- expected: 0 (projection has not run yet)
--   \d document_content
--   -- expected: 4 columns + PK (doc_id, lang) + FK to documents
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS document_content (
  doc_id        TEXT NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
  lang          TEXT NOT NULL DEFAULT 'en',
  html          TEXT NOT NULL,                            -- rendered display HTML
  content_hash  TEXT NOT NULL,                            -- SHA-256 of source markdown for idempotent re-render
  rendered_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Provenance fields per the post-Module-6 house style. Content rows are
  -- always batch-generated by the projection script (never hand-edited).
  is_historical    BOOLEAN NOT NULL DEFAULT false,
  data_provenance  TEXT NOT NULL DEFAULT 'batch_rebuild',

  PRIMARY KEY (doc_id, lang),

  CONSTRAINT chk_content_lang CHECK (lang IN ('en', 'es')),
  CONSTRAINT chk_content_provenance CHECK (
    data_provenance IN ('app_scan','batch_rebuild','manual_entry','unknown')
  )
);

CREATE INDEX IF NOT EXISTS document_content_rendered_at_idx ON document_content (rendered_at DESC);

ALTER TABLE document_content DISABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES, TRIGGER, TRUNCATE ON document_content TO service_role;
GRANT REFERENCES, TRIGGER, TRUNCATE ON document_content TO anon, authenticated;

-- ─────────────────────────────────────────────────────────────────────────────
-- End pr-7-10. Phase A1 schema migrations complete after this file applies.
-- Next: pr-7-11 (drop documents.pinned, deferred to Phase B once the overlay
-- has been live long enough for regression to surface).
-- ─────────────────────────────────────────────────────────────────────────────
