// Append a Phase 5 log section to PURCHASE_ANALYSIS_PHASE3.md.
import fs from "node:fs";
import { P } from "/Users/kevinfietek/dev/purchase-discovery-2026-08-12/scripts_phase4/_common4.mjs";
import { P5 } from "./_common5.mjs";

const A4 = JSON.parse(fs.readFileSync(P.P4_ANALYSIS, "utf8"));
const A5 = JSON.parse(fs.readFileSync(P5.ANALYSIS, "utf8"));
const CL5 = JSON.parse(fs.readFileSync(P5.CHANGE_LOG, "utf8"));
const REC5 = JSON.parse(fs.readFileSync(P5.RECOVERED, "utf8"));
const FUSED = JSON.parse(fs.readFileSync(P5.FUSED_VALIDATION, "utf8"));
const Q11 = JSON.parse(fs.readFileSync(P5.Q11_DIST, "utf8"));
const Q13 = JSON.parse(fs.readFileSync(P5.Q13_BANDS, "utf8"));
const Q14 = JSON.parse(fs.readFileSync(P5.Q14_GFS, "utf8"));
const Q15 = JSON.parse(fs.readFileSync(P5.Q15_CHENEY, "utf8"));

function pmRow(acct, t) {
  const b = A5.protein_mix[acct]?.by_type.find(x => x.type === t);
  if (!b) return "-";
  return `$${b.dollars_per_lb} @ ${b.coverage_spend_pct}%`;
}
function coveragePair(acct) {
  const w4 = A4.weight[acct]; const w5 = A5.weight[acct];
  return `${w4.coverage_food_spend_pct}% -> ${w5.coverage_food_spend_pct}%`;
}

const lines = [];
lines.push("");
lines.push("## Phase 5 log");
lines.push("");
lines.push("Date: 2026-08-14. Applied Kevin's answers from `OPEN_QUESTIONS.xlsx` plus analyst decisions on unanswered questions plus two self-answered items (Q14 GFS invoice reads via vision, Q15 Cheney '#N' data-reconciliation test). No dollar figures changed. Publication threshold lowered from 35% to 25% with visible caveat between 25%-35% (Kevin's Q5). STL-FL now uses 2027-service-calendar projected meals (Kevin's Q6). See workbook sheets: Phase 5 Overview, Fused-Slash Validation, Fused Ambiguous Skipped, Beverage Unresolved (Q1), Q11 Over-Extraction Dist, Q13 dpp Bands, Q14 GFS Invoice Reads, Q15 Cheney # Test, Q17 Other Reclass, Q21 Chef Review Sample, Phase 5 Change Log.");
lines.push("");
lines.push("### Order applied");
lines.push("");
lines.push("1. **Q9 unit='lb' rows** - Kevin: `up * shipped = ep`, `shipped` is pounds shipped, `up` is $/lb. Applied per-row after reconciling `up * shipped_count` to `extended_price` within 2% or $1 tolerance.");
lines.push("2. **Q2 fused-slash + 30 verified pack weights** - Kevin's 30-SKU Pack Weights sheet applied first as `kevin_verified_pack` overrides. Then general fused-slash rule applied to broader corpus.");
lines.push("3. **Q8 catch-weight arithmetic gate** - ep_qty_up_mismatch flag removed for rows carrying real catch-weight signal (`AVG` / `T/WT` / `TOT WT` in description, `unit='lb'`, Cheney `#` convention, or `weight_line_value` populated).");
lines.push("4. **Q1 beverage size rule** - half-gallon+/gallon/liter -> culinary; 8/12/16/24 oz -> service (stays neutral). Kevin-flagged unsure items (CGRVIMP apple aseptic, Cheney pineapple) LEFT UNRESOLVED.");
lines.push("5. **Q3 plant_or_egg reintegration** - Reversed Phase 4 exclusion only for rows whose pack now resolves via Kevin's verified overrides.");
lines.push("6. **Q4 TBJ beef implied weight** - `implied_lb = ep / up` where pack+wlv+item#=blank AND up in per-lb range. Kevin's 4 examples all already covered by Phase 4 Path C; net 0 new applied.");
lines.push("7. **Q12 category disagreement** - Verified non-food shares correct as published (some classifier inconsistency 10-30 rows/account noted).");
lines.push("8. **Q5 publication threshold** - Lowered from 35% to 25%. Cells between [25%, 35%) publish with visible caveat.");
lines.push("9. **Q6 STL-FL projected meals** - Denominator = 7,540 May + 6,190 Jun + 5,130 Jul = **18,860** window.");
lines.push("10. **Q7 duplicate item families** - Recomputed with updated pack reads (still on Duplicate Item Families sheet).");
lines.push("");
lines.push("### Fused-slash resolver: rule + validation");
lines.push("");
lines.push("Rule:");
lines.push("");
lines.push("- **4-digit + UNIT (LB or OZ)**: always split 2+2. e.g. `1412 OZ` = 14/12 OZ = 14 x 12 oz = 168 oz = **10.5 lb per case**. `2420 OZ` = 24/20 OZ = 480 oz = **30 lb per case**.");
lines.push("- **3-digit + UNIT (LB or OZ)**: compute BOTH candidate splits (1+2 and 2+1). Choose the one that fits the row's category plausibility bounds (protein 5-150 lb, produce 3-100 lb, etc). If BOTH pass or NEITHER passes -> `ambiguous_skipped`, LEFT UNRESOLVED.");
lines.push("- **OZ variants convert to pounds** (/16 at the end).");
lines.push("");
lines.push(`**Validation vs Kevin's 30 verified SKUs**: Pass rate = **${FUSED.summary.pass_rate_pct}%** (${FUSED.summary.pass} uniquely-resolved-and-match + ${FUSED.summary.ambig_match} ambiguous-but-Kevin's-answer-matches-one-candidate + ${FUSED.summary.fail} fail + ${FUSED.summary.unresolved} unhandled). **0 fails**. The 7 ambiguous cases (${FUSED.detail.filter(d=>d.resolver_status==="ambiguous").map(d=>d.pack).join(", ")}) collapse to Kevin's answer only when applied against the Kevin-verified-pack override (which we do first) - the general rule correctly refuses to guess.`);
lines.push("");
lines.push("### 3-digit fused-slash dispositions on corpus");
lines.push("");
const step2 = REC5.recovered.filter(x => x.step === 2 || x.step === "2");
const r4d = step2.filter(x => (x.source || "").includes("4d")).length;
const r3d12 = step2.filter(x => (x.source || "").includes("1plus2")).length;
const r3d21 = step2.filter(x => (x.source || "").includes("2plus1")).length;
lines.push(`- 4-digit (rule 4d, always 2+2): **${r4d} rows**`);
lines.push(`- 3-digit 1+2 chosen: **${r3d12} rows**`);
lines.push(`- 3-digit 2+1 chosen: **${r3d21} rows** (e.g. 101 LB = 10/1, 152 LB = 15/2)`);
lines.push(`- 3-digit ambiguous_skipped: **${REC5.meta.fused_ambiguous_skipped_count} rows** (LEFT UNRESOLVED - see 'Fused Ambiguous Skipped' sheet)`);
lines.push("");
lines.push("### Q9 unit='lb' validation");
lines.push("");
const q9 = CL5.steps_applied.step1 || { rows: 0 };
const rej1 = REC5.rejections.filter(x => x.step === 1).length;
lines.push(`- Applied: ${q9.rows} rows / \$${q9.spend?.toFixed(0)}`);
lines.push(`- Rejected (up * shipped != ep within 2% or \$1): ${rej1} rows`);
lines.push(`- Already resolved by upstream pipeline: rest`);
lines.push("");
lines.push("### Q1 beverage size-rule reclassification");
lines.push("");
const bevService = REC5.beverage_reclass_detail.filter(x=>x.verdict==="service").length;
const bevCul = REC5.beverage_reclass_detail.filter(x=>x.verdict==="culinary").length;
const bevUnr = REC5.beverage_reclass_detail.filter(x=>x.verdict==="unresolved").length;
lines.push(`- culinary (half-gallon+ / gallon / liter+): ${bevCul} rows`);
lines.push(`- service (8/12/16/24 oz small bottle): ${bevService} rows`);
lines.push(`- unresolved (no size signal or Kevin-flagged unsure): ${bevUnr} rows - see 'Beverage Unresolved (Q1)' sheet`);
lines.push("");
lines.push("Kevin-flagged unsure held aside: CGRVIMP JUICE APPLE 100% ASEPTIC, Cheney PINEAPPLE 100% JUICE.");
lines.push("");
lines.push("### Q3 plant_or_egg pack-resolved count");
lines.push("");
const poe = REC5.recovered.filter(x => x.protein_type === "plant_or_egg").length;
lines.push(`- ${poe} plant_or_egg rows now have a resolved lb value (via kevin_verified_pack overrides on WHLFIMP / WHLFCLS eggs).`);
lines.push(`- Aggregate plant_or_egg $/lb still flagged 'not comparable' - mix of count-based (shell eggs, hardcooked) and weight-based (liquid egg) is inherent.`);
lines.push("");
lines.push("### Q6 STL-FL denominator swap");
lines.push("");
const smSTL = A5.per_meal["STL-FL"];
lines.push(`- Denominator: **18,860 projected meals** (7,540 May + 6,190 Jun + 5,130 Jul, per Kevin).`);
lines.push(`- STL-FL food \$/meal = **\$${smSTL.window_dollars_per_meal}**`);
lines.push(`- STL-FL core-food \$/meal = **\$${smSTL.window_dollars_per_meal_core}**`);
lines.push(`- STL-FL food lbs/meal = **${smSTL.window_lbs_per_meal} lb**`);
lines.push(`- STL-FL core-food lbs/meal = **${smSTL.window_lbs_per_meal_core} lb**`);
lines.push("");
lines.push("### Coverage before/after per account per category");
lines.push("");
lines.push("| Account | Coverage food $ (Phase 4 -> Phase 5) |");
lines.push("|---|---|");
for (const acct of ["TBR-FL","TBJ-FL","STL-FL"]) lines.push(`| ${acct} | ${coveragePair(acct)} |`);
lines.push("");
lines.push("Protein $/lb (Phase 5, coverage stated inline):");
lines.push("");
lines.push("| Type | TBR-FL | TBJ-FL | STL-FL |");
lines.push("|---|---|---|---|");
for (const t of ["beef","poultry","pork","seafood","plant_or_egg","other_meat","other"]) {
  const anyPresent = ["TBR-FL","TBJ-FL","STL-FL"].some(a => A5.protein_mix[a]?.by_type.find(x=>x.type===t));
  if (!anyPresent) continue;
  lines.push(`| ${t} | ${pmRow("TBR-FL",t)} | ${pmRow("TBJ-FL",t)} | ${pmRow("STL-FL",t)} |`);
}
lines.push("");
lines.push("### Cells that changed publication status");
lines.push("");
lines.push(`- Cleared 25% threshold (now published; some also would have cleared 35% pre-Phase-5): ${CL5.cells_cleared_25pct.length}`);
lines.push(`- Published WITH caveat (25-35% coverage): ${CL5.cells_with_caveat_25_35.length}`);
if (CL5.cells_with_caveat_25_35.length > 0) {
  for (const c of CL5.cells_with_caveat_25_35) lines.push(`  - ${c.account} ${c.cell}: cov=${c.coverage_pct}%, \$/lb=\$${c.dollars_per_lb}`);
}
lines.push(`- Suppressed below 25%: ${CL5.cells_suppressed_below_25pct.length}`);
if (CL5.cells_suppressed_below_25pct.length > 0) {
  for (const c of CL5.cells_suppressed_below_25pct) lines.push(`  - ${c.account} ${c.cell}: cov=${c.coverage_pct}%`);
}
lines.push("");
lines.push("### Q11 measured over-extraction distribution + threshold recommendation");
lines.push("");
lines.push(`- Invoices scored (line-item sum vs invoice header sum, post-Step-3 fix): **${Q11.invoices_scored}**`);
lines.push(`- Quantiles: q25=${Q11.quantiles.q25?.toFixed(2)}x, q50=${Q11.quantiles.q50?.toFixed(2)}x, q75=${Q11.quantiles.q75?.toFixed(2)}x, q90=${Q11.quantiles.q90?.toFixed(2)}x, q95=${Q11.quantiles.q95?.toFixed(2)}x, q99=${Q11.quantiles.q99?.toFixed(2)}x`);
lines.push(`- Invoices above 1.15x: ${Q11.above_thresholds["1.15x"]} | 1.20x: ${Q11.above_thresholds["1.20x"]} | 1.30x: ${Q11.above_thresholds["1.30x"]} | 1.50x: ${Q11.above_thresholds["1.50x"]}`);
lines.push(`- **Recommended threshold from measured distribution (q95 rounded up 0.05): ${Q11.recommended_threshold?.toFixed(2)}x**`);
lines.push(`- The old 1.15x threshold flagged ${Q11.above_thresholds["1.15x"]} invoices; the recommended ${Q11.recommended_threshold?.toFixed(2)}x flags ~${Q11.above_thresholds["1.50x"]}. Lower false-positive rate on legitimate freight/tax variance.`);
lines.push("");
lines.push("### Q13 measured $/lb sanity bands (per category)");
lines.push("");
lines.push("| Category | n | Q1 | Q3 | Multiplier | Band | Median |");
lines.push("|---|---|---|---|---|---|---|");
for (const [cat, b] of Object.entries(Q13)) {
  if (b.note) { lines.push(`| ${cat} | ${b.n} | | | | (${b.note}) | |`); continue; }
  lines.push(`| ${cat} | ${b.n} | \$${b.q1} | \$${b.q3} | ${b.band_multiplier}*IQR | [\$${b.band_low}, \$${b.band_high}] | \$${b.median} |`);
}
lines.push("");
lines.push("Per Kevin's steer: seafood widened to 2.5*IQR; produce narrowed to 1*IQR; others 1.5*IQR.");
lines.push("");
lines.push("### Q14 GFS invoice self-answer");
lines.push("");
lines.push(`- Model: ${Q14.model}. Invoices probed: ${Q14.invoices_probed}. Cost: \$${Q14.total_cost_usd?.toFixed(3)}.`);
lines.push(`- Result: **GFS invoices do NOT show per-line case weight for 'NxN CO' packs** ('60x1 CO', '4x6 CO', '100x1 CO' etc.). One invoice had a weight column but it was empty for these SKUs. No case-line-with-weight found on any of the 4 invoices.`);
lines.push(`- Consequence: GFS 'NxN CO' rows stay unresolved. Recovery not possible from invoice image alone; would require vendor catalog (Q18).`);
lines.push("");
lines.push("### Q15 Cheney '#N' self-answer");
lines.push("");
lines.push(`- Method: for each Cheney row where uom_raw='#N' AND unit_price + shipped_count + extended_price all populated, compute implied per-case weight = (ep / sh) / up. Check whether it falls in the row's category plausibility bounds.`);
lines.push(`- Test result: **${Q15.pound_n_test.reconciled_as_lb_pattern} of ${Q15.pound_n_test.tested} tested rows reconcile inside bounds (${Q15.reconcile_rate_pct?.toFixed(1)}%)**. Threshold to adopt: 80%. **Convention ADOPTED.**`);
lines.push(`- Interpretation: on Cheney lines with '#N' uom, unit_price is $/lb and shipped_count is number of cases; per-case weight is implied by (ep/sh)/up. Already covered in the corpus by Step 3 catch-weight arithmetic gate (these rows carry weight_line_value populated).`);
lines.push("");
lines.push("### Q21 chef review sample delivered");
lines.push("");
lines.push(`- 30-row stratified sample of protein/produce/dairy SKUs (10 per account, weighted toward spend, mix of confidence levels).`);
lines.push(`- Delivered as workbook 'Q21 Chef Review Sample' sheet. Column 'CHEF: agree?' left blank (amber) for sign-off.`);
lines.push(`- Analyst does NOT self-validate. Chef marks AGREE / DISAGREE / UNCERTAIN.`);
lines.push("");
lines.push("### Analyst decisions recorded (distinct from Kevin answers - revisitable)");
lines.push("");
lines.push("- **Q10 orphaned line items**: KEEP. Filtered on read; no cleanup migration.");
lines.push(`- **Q11 over-extraction threshold**: measured from post-Step-3 data (see above). Recommended ${Q11.recommended_threshold?.toFixed(2)}x from q95 rounded up 0.05.`);
lines.push("- **Q13 $/lb sanity bands**: measured, seafood widened + produce narrowed per Kevin's steer.");
lines.push("- **Q16 fees**: verified non-food (245 rows / \$1,245). No change.");
lines.push("- **Q17 'other' category**: 16 top-groups reclassified into real categories via description patterns (sorbets -> dairy, condiments -> dry_goods, service fees -> non_food). Long tail stays 'other'.");
lines.push("- **Q19 failed-invoice rescan SLA**: 30-day policy adopted. Backlog audit to be done separately.");
lines.push("- **Q21 fresh vs frozen**: sample delivered; analyst does not decide.");
lines.push("");
lines.push("### Still open (need Kevin, DO NOT guess)");
lines.push("");
lines.push("- **Q18** printed / scanned vendor order guides for Sysco / Cheney / GFS / FreshPoint / Samuels. **HIGHEST-VALUE outstanding question**. Would eliminate half the pack-size question class permanently.");
lines.push("- **Q20** delivery-fee / minimum-order schedule per vendor per account. Without it, true delivered cost unanswerable.");
lines.push("");
lines.push("### Dollar invariance check");
lines.push("");
lines.push(`- **${CL5.dollar_invariance_check?.pass ? "PASS" : "FAIL"}** (${CL5.dollar_invariance_check?.issues?.length || 0} issues). Every dollar figure - reconciliation totals, spend by category, protein bucket totals - byte-identical to Phase 4.`);
lines.push("");
lines.push("### Cost tally");
lines.push("");
lines.push(`- Q14 GFS invoice reads via Anthropic vision: **\$${Q14.total_cost_usd?.toFixed(3)}**`);
lines.push(`- Q15 Cheney #N self-answer: **\$0** (data-only test)`);
lines.push(`- Total Phase 5 API cost: **\$${Q14.total_cost_usd?.toFixed(3)}**`);
lines.push("");
lines.push("### Deliverables");
lines.push("");
lines.push("- `~/dev/purchase-discovery-2026-08-12/PURCHASE_ANALYSIS_2026_MAY_JUL.xlsx` (overwritten; 36 sheets)");
lines.push("- `~/dev/purchase-discovery-2026-08-12/PURCHASE_ONE_PAGER.md` (Phase 5 section appended)");
lines.push("- `~/dev/purchase-discovery-2026-08-12/scripts_phase5/*` (Phase 5 pipeline + all artifacts)");
lines.push("");
lines.push("### Phase 5 pipeline commands");
lines.push("");
lines.push("```");
lines.push("cd ~/dev/purchase-discovery-2026-08-12");
lines.push("node scripts_phase5/00_read_open_questions.mjs      # ingest filled OPEN_QUESTIONS.xlsx");
lines.push("node scripts_phase5/10_validate_fused_slash.mjs     # validate rule vs 30 Kevin SKUs");
lines.push("node scripts_phase5/12_q15_cheney_pound_n_test.mjs  # self-answer Q15");
lines.push("node scripts_phase5/13_q14_gfs_invoice_self_answer.mjs  # self-answer Q14 (vision)");
lines.push("node scripts_phase5/20_apply.mjs                    # apply all steps -> recovered rows");
lines.push("node scripts_phase5/30_recompute.mjs                # recompute analysis + Q11/Q13");
lines.push("node scripts_phase5/40_q17_other_reclass.mjs        # Q17 analyst reclass");
lines.push("node scripts_phase5/45_q21_fresh_frozen_sample.mjs  # Q21 chef review sample");
lines.push("node scripts_phase5/50_q12_q16_verify.mjs           # Q12/Q16 verify");
lines.push("node scripts_phase5/60_build_workbook.mjs           # overwrite workbook");
lines.push("node scripts_phase5/70_append_phase5_log.mjs        # append this log");
lines.push("```");

fs.appendFileSync("/Users/kevinfietek/dev/purchase-discovery-2026-08-12/PURCHASE_ANALYSIS_PHASE3.md", lines.join("\n") + "\n");
console.log("appended Phase 5 log to PURCHASE_ANALYSIS_PHASE3.md");
